apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- components/image-registry
- components/nfs-provisioner
- components/oauth
- components/openshift-gitops
- components/openshift-pipelines
- components/sealed-secrets
- components/tenants
