apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gitops
- image-registry
- nfs-provisioner
- oauth
- openshift-gitops-instance
- openshift-gitops-operator
- openshift-pipelines
- sealed-secrets
