apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infra/gitops

patches:
  - path: patches/applicationset-cluster-config.yml
  - path: patches/applicationset-tenants.yml
