apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: image-registry

resources:
  - ../../base

patches:
  - target:
      kind: Application
    patch: |
      - op: replace
        path: /spec/source/path
        value: clusters/cluster/components/image-registry
