---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-dev

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-team
  namespace: engagement-sim-dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-team-reconciler
  namespace: engagement-sim-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:engagement-sim-dev:reconciler
- kind: ServiceAccount
  name: engagement-sim-team
  namespace: engagement-sim-dev

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-cicd

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-team
  namespace: engagement-sim-cicd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-team-reconciler
  namespace: engagement-sim-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:engagement-sim-cicd:reconciler
- kind: ServiceAccount
  name: engagement-sim-team
  namespace: engagement-sim-cicd

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim

---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-team
  namespace: engagement-sim

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: engagement-sim-team
  name: engagement-sim-team-reconciler
  namespace: engagement-sim
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:engagement-sim:reconciler
- kind: ServiceAccount
  name: engagement-sim-team
  namespace: engagement-sim

