apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
data:
  disable-affinity-assistant: "true"
  disable-creds-init: "false"
  enable-api-fields: stable
  enable-custom-tasks: "false"
  enable-tekton-oci-bundles: "false"
  require-git-ssh-secret-known-hosts: "false"
  running-in-environment-with-injected-sidecars: "true"
  scope-when-expressions-to-task: "true"
