apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgDRnu2g3xmpymdRix6ryeC0zTmDnAP4bHedXzQTrB9di7L9G/zvjOCKycAyxRPbZARqs4Avbqr+GtyrnLf/orQVEzJBkdPZYuSYVAbbGa91z/BB3DIbbSqqCFgrLIucNFW/qSOpaH4D1/93dBTtkU9vLF+WR0SzZlBrE2NVaOHsKcKV5/2KVFxh6aKeJ/HDIzH4uPf0WMfsD6/0zyqc566SbiVQe5Di8Wvh0dSnW8QceS38WZTHjcABLp4uaTkl115Od5OFz6ofbNYFzSaB67wme0SNHo8pn6Zy2foEEKsx6dcOVxjgbHHHCp8xun2K4n6foPKOLTAFbLWHVlXhHNbMgyVkyQ0RZ3o3i55k5rUoWtsiASFR2LQwqiGfMWep7+aHd8Ta26WcOKhYr9ZmcgKcx6VKHt/svMXnDno7HfNG/5q0Y+vnd3rZJb4KheyP6AGgM/oou38Mbn3vApe3s4CcgFlUS8lBrop+Q9yrnp//D2gvd5XRJfKVyNPPdmcj4PNin2VrgTP0zloI7utFO2giQ9F9OstMieDZ0EYkSyiTm6n/biF3TeblHx3sLIhzFWPqOt9ErMfHAHT7ng/Z84V26SncVPTS5aNGGi7fAdk7o4NujVOpgvk75t1WAxlq9AzPjtDkJPGnXWnRAqHN2peyXU44SxZ85DlxAFRiqVAth9o+wZsTdsUVRY2VhJJ5h/H/yZHsN8KzDyHEhzwKvWYUUWZX6NPPHHcgHaRQ+OcNd8m57J70axz8oO74rAn7cwtht9bzzRnclbz2Y0LgBuyvrsZ3l1lP91oFZsKBL3QFN5qg5Br6iJQyqilf9eDEhIQIHfBX5WI9Aun17443wEE6NzuncuTNd4Hr8gUSxWfaYfDk8JXJfNwYS+8=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

