apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgACnH987Q/yysQhuLJrQvJ/1DolglWfGUhjz46mEam3wSCrbFSpGJZVQzEpKrvpoNpfncQn4DsXCig3MbeZQ602XeEXiK1Y0Y055zIFBYaMyBDD2n/l4u7aVbo1t3AR8q+L+KoqABlz4EBrDagNUh284xaEC8/3QJbgKsl/SwpbTO0noR0KGVgUJpXt7oVWbUnhSCg1hj7TTY7qqmvfRdZyH0HVmMzy1VFbDfG/MYBb4dyIqttPsnvcb7UcJ5hEOrq4co6U/8XIl4ZlMngePoKDDq57LfytbIPpFuwnuVRgzy3cLqlutr4SAvkc06Bdq4DJTL5d39fLNLZ2DyAcerLk9LSqC55pkH72ctjRjkhZHJ38VSo7ZVhGnsmQt0+pF8pwwwGiAmSEfp4sP/hKfY9xxyjm2QD1an8sO23dChoub6xUotxyIDlfWYTaJmCF4zJWBjG7asxoTtschnTqc9ANeT2iCrqA9Ov3a/+oC4/y5cqtQgryJPn1RaeCiao9eqqornErfpj1J6W9jEluOZYwbQyqarjrVF3VJnmxtcg+t7EuKnSxjW7Ie6z8LTW6RO0uQkIUJ+l6aSDdPceDbSAkRDHncMV1zopGYd8z25rGTBIE9L/vAWsKpwnrje4gC8jYwf4Kp4muf42mEiq3XfgNyTahFhJ9cMdeWFLzi8kK9T64AaHq2S9HyPzNfA//u/Ude+XDoeYKlvt32tDQONXaqhewPLuvsm88gSvVnOiMYlmZ076SCAJ8PAMb9MNoo4GPyLE6wnPIopwkFEj8MynuRTWM195QL3vSfCVZVsaIl7giKPXSZf0dqGlPU9ov4Qw6AgRJtl55WIWgSkKe7xoLoj66Z2BlAJcJbM88RiLq3muQPiIo35zSIHQ=
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

