apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBxr2ZhC+sR27CLrog3aUB7UvJQTdvz/dsIyyYsV+9GRMgIodsJptCeXfaHSWaUpYoICXDuLVVvHyXC2QtST2x20PwlkYZ0qbGKPNm+SgONkIBlucAcZ3cNL9bUi1+17UEQHtPBLUQJd8m3QcF9gyL8tc0jXJuQQ2aca1qQ59vRVRo9W2LA24qplf0LcS+TgPji7EhY2JWeEs999fJjfyc+8u3Xk6jLstxeGokmDohm6/89UsY2JazvRwrif78MaKgXdjQqFNKyO/fZ/ldEni9u2pJ8Gg9lTDhiWPhJTXKvS6+IT/f5jXIOXLw3VpS+MTZwYLlNdVo8s1jeOqej/W48/xC/zi8eIohOr0a60SOzglEC0L3xhhS4NZCXgWP2BzZ75umFce2vVKBAJqy+3Hu5jkuFy6wZhbjTDu3U4yW2YfxtAVkUqThOzJTb/mDNkwljjtYDBBGXRrhkVEimJf5swVNF3pBiqWtfF/indOSo2lA5f50wmz7GZdN/daMN3+RJkLujI3RGESfJ6glnoFgRo3E2V9ktRjcDWGWCzCS+un4JThv70hubSQklGlnRUA6WJLXZ3tfc9p13FBbiXcTTfpdCpd2ozbqIkwDYjM5XZZoBC939kZys8TvKAukjomSvk8RDBo4bk0Niuq0Kt7zTmQq3/DTRJpZz/uYsDtxJORJhKm6w/qkTAOmJXNYV5Rpo3YCoDnLZpL4vwO7jhV4fU1FGBb8PV2N3ounDYxXAJbExQaEPfrOKJ/rzMK0r4VOM5ymX73qFqsLO5xQGijPRR9CY7CCNR0qnrMVzDQvnxkNWF1U9MXbvDTn6j4Uguuc2UI7APAzefMqWEN4eBCCyKh4Dt9uXT3j8yycLNNzBp8gdztNE9SIIC4I=
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

