apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBqUkuLMRjITLhO7Y/YqJ5lqZy+vY4JCzepuu4oNL6FIQHx4ChaMgLBcCF7v5PdpCwk0MGQd6EKs0ePnia2T2lM7nOfXuWZhc1oIsuWamPHj61x44LOwLFXcsMxG4fWSilUwk6kipUi2b/5z5kiGBUfrjhJBGUBATAeY0KM3IlsffDoGIWGrxZI3QLh9hVQnEiRHJCkqu9M4FsebRIRx6iykuU+t4W8R6iHH9Fs/eQD30BtBqlVN0fDnmcICJPb1h9loqqISZWUQmEugdugKfo/4Misr+ujvpFYVbpwYqSMzeQ4wyBwDSxNqcrEEhDO+m4m+rURyxxwExQAj16FGfr6rI5wPyUGLUodiGpHKWEA2wxj13HCCQUs2WJcj0qAZYxHne1XTtOIeUZx43bG9458DzxZQD2cWKFDx8PYaFl+2r10hwWw7+VcKGK2hydQwX/Iy/bBeC4+6Oqv3aTy87KPjanz+iv4zrnQloZmDWjeJ33gNumZt50z7pvPoAhLHIh5GLlrKfQ7yGYTNyQ8APubVnPEdj6k8ez4lgv3YK4w/KumDl/tPBHEr8qX+CO6znE6DGkmPbi9p8uJnMxvZDBhaWLA1iqnCdQhxIITk5BksG2z5MZzVIL/rRVzkO/VX0ndkMLYh7Re3cktxDhQLsK83J5BkHMxSH1bDylJHQ46oUeyqlWFQISq6OKcO2V0nRqhJyrPX9m16eLq6TSAEDNCpjnM/97tnPKlg95Gki6zczsTl/2PKsVLeUuoNWycAsK18zQnANGiMjg2hf8aQblTkozV0g==
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

