apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgCOif6kzshnZUaJswdVnfn8tGm6XGOa1/zyg38/1ZX0QCnlXHG4AYqvqHwoSF2S17YrMFhx6TMJhDxTWA58oH1oHHW1sSiu+Wz8IE7hIE4CggAN/ccv97aMJFCgEjzXwKyNG5CjLHf1F8kliofJUTxTo0KPABUwzYM5WWXOG2aY3Z31/MKJ7Te7xLQvL1wtvo/sL4HsJWJH1TW4wOvUqoIfsDNRLBtWPOSx7WoohmEqPzSPPBHnHHCOqjSLeN8r1+WV54JBgrKWJelK7Tutclpw37/ob4kuaXC3SiWmdokS9nudSMqYNCrjA0SOog2Nwh68igrMPA8ypG8VpB7p6o+/uPLzpZojMhdpwgd7PyxeOZgTfRq0reSNTpcuDVBWXZ91rYTtqfgiMCIxMiibpHjDbvrgEq9zmxSKwOyilU+73G3sLQV4b3n24i3SDL91mLW+dRVdykNZF24B/lxj2Elx0JVsnE7Q1VS3YBVRWZJEGJXUWsshxQDI2tVG48jslO114ugMnNbTRkU7oNU7AKlkYDo920L1v+Ld0HRUtYLljADOR0xsy0Tzg+IerWZ1XFUlQz1oYuPJBx8mCEX03PzMzRmsuZ/YGUM8+XNoh9jAv4e2R3AMSLQJFBD0QaR2gBS2sU2o3L1ljMFlJlxBzDNy6SunKZsPnj3zohr7VFOMoxKKSbFpWEq/IJ7GhKRq4GAomotvs5ogbUv4CDb+hIU88SzmYn7rEqI8GNfyhbEg0moEaevPfh1jhGYH2U1yuuNSOBkXaw7QDTFLbvjdk7WNGWm/GGWSu9t3mH+7xPcQI9V6mv/IKikqFZpZc5VMHIqwsMCB8dLZG6kR7HKGI0z9BZ1ozydzo1NMB0MUOb2ZrXAkn3jm4rsNMUI=
  template:
    metadata:
      name: htpasswd
      namespace: openshift-config
