---
apiVersion: v1
kind: Secret
metadata:
  name: repository-ocp-config
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/stocky37/ocp-config.git
