apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: PROVISIONER_NAME
              value: fuseim.pri/ifs
            - name: NFS_SERVER
              value: 192.168.0.100
            - name: NFS_PATH
              value: /tank/openshift/storage
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.0.100
            path: /tank/openshift/storage
