apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpasswd
  namespace: openshift-config
spec:
  template:
    metadata:
      name: htpasswd
      namespace: openshift-config
  encryptedData:
    htpasswd: AgAP1/W1PSftdIT4hk8qkl7Nkc8dpM+yOASYJQY5rWOuLpSI+jZWgui8CPnUMS+Ca2gd6mWkQdIVRB/iQ0JlpIpLQGUcxYN5nqafe3BqKh2smcW63XmF+zv1vb02P+IucLfcAnVNdaPYbljHINWjY6CN7xQTpm9l1hWb+wWM1Fqolq3amiJmOyGaqUL7qZ6ge0tjfb54F1Pemqnd4Qd3+tyRimY5wcZsmJMHdG3qgbOijNTygLRpC2SjQrkVn48CEQUbk7685uE4/2LJDO1ALgj4hsFIIbD4qGrz3F7qg6es78m8RfyHeIjMs4UyCRvthOkRRaHGVmeS7iWcNLu1lvmB6kAcex09321fLAEB8XA38iAtJlm0MQLPqYzwJ0M67LEgf/A2OdNU1zZZN4Mamsu8gCD94Yj8hfLHmIkQLud66bxhqU5BLB5FctVnbQPMkZ8AhOq2yKrAfj1OzUMbQTHggJInh6YUPGMUgr5lkZfN2n6wURBECMugmd4LCYO9UI5QkHG4rSH6kU29v/1QgAyURIQ6KKzoZ9/l+XP1r1v6tfs8pGfcZS8mfTVbR195Z+7O+Zbt14m7F0YFySQZr7oo6wXRyVAkMSEWMHSPwMSaQyuLHEbK61wjzx0BPPh1jrr7pHan+D+ikzI6iOYGdvZ59+evEC7e1LEpAOiJeCN1wSLt0d0O7T6qgYbKGhULAQ9MZF9vyBQ7gXZ3goswq8FPxpbT2BIkmjJscIYtOwP29/1Yw8ihhtMNO2HPBwGRZfPbq8RZHWiOjixuP0fsgPPvcF2Zag==
