apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-configs
spec:
  generators:
    - git:
        repoURL: &url https://github.com/tom-stockwell/ocp-config.git
        revision: &rev apps
        directories:
          - path: clusters/cluster/components/*
  template:
    metadata:
      name: '{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: *url
        targetRevision: *rev
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true

