apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-gitops
resources:
  - application-cluster-config.yml
  - applicationset-cluster-configs.yml
  - secret-repository-ocp-config.yml
