apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
spec:
  generators:
    - git:
        directories:
          - path: clusters/rhpds-demo-gitops-cicd/*
          - path: clusters/rhpds-demo-gitops-cicd/bootstrap
            exclude: true
