apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- https://github.com/redhat-cop/gitops-catalog//openshift-pipelines-operator/overlays/latest?ref=a8b5bf1627f1d080268d83ebc47b0c8c8acc961b
