apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
resources:
- namespace.yml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.17.5/controller.yaml
patches:
- path: patch-deployment.yml
