apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
      - name: sealed-secrets-controller
        # disabling automatic key renewal - unsafe for production use
        args:
        - --key-renew-period=0
        securityContext: null
      securityContext: null
