apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - config.yml
- https://github.com/redhat-cop/gitops-catalog//oauth/overlays/htpass?ref=a13bba3861f95583ef22678f00907ae220624a65
- secret-htpasswd.yml
- cluster-admins.yml

patches:
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: htpass-secret
      namespace: openshift-config
    $patch: delete
