apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgDAnCMNOOlPikETq1/8J60B1vS83Wv/ejjafjhYrp7JLyrCwPHf7LzieNWqWQWbPVA1CkUwdyeER5HieDlZ12nt2sHd2H1UqrnKDASWK8XcoiwkWX7uhP0dFhnvjtUrfD1AN8G5yU5QESjA7Ho+f4HC5py4ba3dliP/4G5lC3Jtzi4J9hRU5rQABQsWXQDRcA/EmS1jUfAxkhvZxmO1rR/Y+1qSwc9GFac39zS9VnBCYKbG73fblgbuxYGtqoXSLaZ39KqeC0DZVbFa7eVtBoFO/v3828QHPKOvSBuewEX0ZJK2nLydzrzWvGYuTaJVQ5RDEchCUs4vR3ueVj5hN4sgJXUH/+PC25yjaL9ec9+PmOOnoNjIjfvyaWZ8DwEvhHDBUM3+QYhFfKVMa7AoW2yYmkXRXrq2ZBYJ2ez29pNm6Oo44kJMNJR7hIQRKadGswtQvGIdhlFCUF0hZL804kx4mw6nkbjuMGcHBWK8BzRa41eKfz3eUZpvRNvzCIz31hPWNMCD8YHO2lEXhmBK+eRXUxIxJUL7RpAFvYCATCKm4R4Pkuv/PiRUb5IAIdjcjc36KCqzsoqIAacvkxg8e1Lj5HnmjBGS8icC+8wkKvHO529oWXKcxpnwcplIQ2h840OfWj6YkiuNCb3wlOZkfNzeuet/FvANIAshqgaUUuCLulAzEOYKYGjUPu/TyBohE4TPT8B6tURL4Bh6JCvI7uNTbk83tcPdmr+4xtx/s9KAZrJY4nTYRW8nOZqGNWU66j9zRRVXDlLGW/g++S/K9QiPkkEfXlTiGl/hX+ZHrDbRwluQ+3w7GWyBtOOCAW7kaeKWtLGrKCklHa1LwLRNCZrRlW36OPib2DTykklRNa+OEzaj5/9I+In/P5o=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config
    type: Opaque

