apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-scc-hostmount-anyuid
  namespace: default
rules:
- resources:
  - securitycontextconstraints
  apiGroups:
  - security.openshift.io
  resourceNames:
  - hostmount-anyuid
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: use-scc-hostmount-anyuid
  namespace: default
roleRef:
  name: use-scc-hostmount-anyuid
  kind: Role
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: nfs-client-provisioner
  namespace: default
  kind: ServiceAccount
