apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tenants
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/stocky37/ocp-tenants.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
