apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tenants
spec:
  generators:
    - git:
        repoURL: &url https://github.com/stocky37/ocp-tenants.git
        revision: &rev HEAD
        directories:
          - path: 'tenants/*'
  template:
    metadata:
      name: 'tenant-{{ path.basename }}'
    spec:
      project: default
      source:
        repoURL: *url
        targetRevision: *rev
        path: '{{ path }}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ApplyOutOfSyncOnly=true
