apiVersion: v1
kind: Secret
metadata:
  name: repo-tenants
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: tenants
  url: https://github.com/tom-stockwell/ocp-tenants.git
  type: git
