apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines
  namespace: openshift-operators
spec:
  channel: ocp-4.5
  name: openshift-pipelines-operator-rh
  source: redhat-operators 
  sourceNamespace: openshift-marketplace
