apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/stocky37/ocp-config.git'
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
