apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-pipelines
  namespace: openshift-operators
spec:
  name: openshift-pipelines-operator-rh
  channel: preview
  source: redhat-operators
  sourceNamespace: openshift-marketplace
