apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: cluster-

commonAnnotations:
  argocd.argoproj.io/sync-wave: '-2'

resources:
  - ../../base

patches:
  - target:
      kind: Application
    patch: |
      - op: replace
        path: /spec/source/path
        value: clusters/cluster
