apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
spec:
  generators:
    - git:
        directories:
          - path: clusters/homelab/*
          - path: clusters/homelab/bootstrap
            exclude: true
