namespace: sealed-secrets
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yml
- https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.15.0/controller.yaml
patches:
- path: patch-deployment.yml
