apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAtwJK008ImKFFSARAwFAiS8fOMOSsTCqTMDl+PXf0T/KHfoA6kpe9Sd4MKDktuMhbeh/J1nD7waSHfzDE+Mo1ErYC5nmDU+LFMYWDs57mNCJ/q6pI2EFAc6vWZWnE1vaQNPaOPXleAGEx7IRwoV0cvc+JsrUjK/FkcTMtjgLLKEVV8gQ1IN3MBvGHhsO6PH/gQ3YI83wmwkF2Rpay2x0ISAFgoEtTLPGLSmGWVnpRi1IyI5EHrs3cAQkknuzGfxx6LRYCpT6qgtP5gOmxXGzhT8Tkuc8u/ilw0YySzI9wZaD68qX9VJNLFLSemM98QyhfXVkIU+26jsPRr86l6GlFRu/JzAg3RCs4RPZ9HZVXMV128QPARJ54LvCG8cuiqjBkKabU9uExcro7KUMkbWgR5cQAUKRebEKq/cNcTgKXZjYEFG0pxuOdZEs79RZIXTAFK9MFqPuBbQ18S13y8XDkt36poP831fhFTI/DLBXUutzSAQANp86/a0+divS0uL5Nn49icj8Q4Ew9E2uCaBmXC/dd+44zMd6C1H+yMfoD5KJBcskYXsPtXDb4li45W7Tk9U/olQaAstOVNCY81W76SkrY+pNnnElP1LXcAw+196r5+lWWgPA6bsKbre+U4HxUW6Kd6P60pZKcDrFNdScKtQfrHoVZOqvMF4ij/CD93NlAD8tx5hmuJ7vSvcuIw6339YsqWtN8g7jsYAzhrMq/1AlvcMGj/xA7tmSwgqZSn2FS9whsrSdHVTNnkMJu45rVeCLd0goz8dQQdzgm82BaEzJKlikVVbX/7wyb6Dt/GWZVRS73ADGhxubypf8Ix3nyjWhuHNOXqJUIXUvzRLFtmUKp9sEHYbKqx1HTYYrs9B/bd5kulTd0=
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

