apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgCVCX0yz2/n9BtlJIUYB+MVEfL/tLLe29ioqceV6gbHP9bJ5fSbRNKVbv+AKYyDRWcAeEZi1RG4Es4RUG1sQcKnY9CBuYoZdFUz8r79PMuboFC87It01soG1dlANXtCU/l2HWqecdNPvNAcANlKQ6iGEiDO4o8KCWQ2y4fznuIrfnhgO2zljKsKySa4H4zG/ZxbcZMPop4lo6lOcjgBYSxujxpVq4Pz1R26maffLISAGN7No/XpCiHFnIOUNA02JXxMXLxanymN14HZq4l8yBOe8KZxy4Ox0SiQxV+NOYXoCBAdzI5E8llt6UNX0xn+6WE5F+YDoKE7Bxoct0O1xET4bWtzFHPY2MfOKaDMTD2Jk83f4IoQhQAQzl6cleqV7HJAv5cLQ0vC1sEsxAw9WZ52QDIpABTObNosLUT8qJBr6iSJqk0xP4M65/qth5hhfK5r+0JPUpm5DMvE+BlCo1kLCZrt7VV0RZCzeoPoTVkFCfy8wlWc9EnMrXKo3qSzqzGwojyOJ3EDsvmhdvTqGecFXxDEkV2BEpjVOJ96b42+kmkAtz0DXhRcnKU8I64+h8zJRGLwPvvxrp1xjAD/Dz14K5NonM93gYaXMpnYQ/beom2oN5+6v74SmFSLTuYw1shnYnoQ1r/Vzkwi3Niq5efbDdlRgbsAq/n51PJAYF54X71f91ocDFSJss6qa7nnS+y/WcEJ9MQwgN8tu9zTR8bzCmb4o4PAJG1RzLtaa3bQZ5oTsmSvR7ZB8DEl5f0q0wSifKlDJUSOwEgg3e3by8FxL6mCEw==
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

