apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAHNOrfqddxdiKRS47x9dchFgYLkpBIp1zur9iIPzmqYpLSahipP6Qq6RYSnkdT9H9k8c1GC+5usJZZVV5qTsgYbtkb32EBtEE5EbUW3ClkT/Spz12/b687Sm0pkhjCncl0QMUmoN03m6lcHm++OZGldijo4JRvQC+k5kbhSpJQaa633JPmQMMNZWNGZYJBs4GSanFHtSsFOSLiit32KLDRyfFmcnmLNyb8Lf3lOnPpnV3daB+GFWmBW3Ngk2JJRC116epGQPfVIS7T5N8/I4QUf4O6AgmPy6EP/MG/fBHa+6zmdAMkp7SKvfJBU5j2qgAHSFVG4bShK2re+oSrTF48SW9Nmye9cPdYMydMYmYDh1ydeHuTF3oj2ImKPkE7HcNxhtymB5G7A3LHCkNJjQwg7nvADscBjDUidj5Se+yUOsuv6NZg4vhwDE02EeSAm7eZ9ygPkzA5PgYd59d0z9W9V9oGMMMxSp4qAGD4EvuLLzoPBFVuXA6IWc3ydnRHZEYOmmDBBOdSESC/NVnS6Gp+LmcX4wnNAnJNrrZ8PXilBrg7CutzImQfLEMQqry9xewPadVlJ66VgWl71YJb6L1Mr9wNJq7jWSx2UnVGDxCkrrb0FjimwnTbK1VswLilRZ7f2wpvZauv70xqUeYMjEicKQMkFpOegGbT7G5Xw+VBPzA2/b6hGy8FwOdzvukwMpL/zrZEFpftsrWr2CVjATWq/ojWbktoE01PVV3azkJXiK1w6583mUIOzzwMp+3rcdJTC/KcSuwI5bghx5V17uVeCk6pNw==
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config
