apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgA84yHXtEnwF+YcA6GLzGlp4QnBKHmM1CiSVR3C2ib66CVpozVlrI54c9IKTJNlywHbzHHnt1yfyIvmQlByzAYasLz+T+hHo+pDNPGCk4EglcWWFSaFSkVpK6Y9pUhbgnUS/V+u/F1pA7R20ORlvbY8w3AYdSUZDQPQ/vGf/fUCMULbOMJIWskF2peCnlV+bw8yqp97dS/U4xmPBxhRT1fv3aFzXV34fAJ55Ul0U3S+JgyqKiWJeA/dL8lCTRqWjSKMULjDNfT/Zurtu7B5llI4rQH8DbqVainZvu/qUSVm68EC13h1VvdO9smuiRr8/swJJRK/3yb4diQ5I3fULhOfBeDIXx1nQqqVzHpb/pwCY4y9kNB5pZ7wz/apXp80qffE5g1M56JuWyo0Q7FjXsskyUjr88j5BV/DGQm23Q9d/cTR9+FtGy3y8LlWIy+gGV7ut3C0nOjobOQjzFtjwgGhxrHLfdyX82+xmS04Hu3wwLuUNOfEWRkPNV3Htv37gl6Iapi9oCeDKhZaGOfGoRrOUTq1wwMsqb2XVOqiQq2Wn73gdVAhe3goV01lDrsZckZa9D1vk6kQkeIxagv4SnwnvCPEoiVeZqUtXjjirkhFm//65Cr+8Q/DoPWNPqIMBBjL1K92CRkeek39Rq8sNXSWhULKG7CtmZW+HcsVm22no76s+s34KhVn5lgAqw0eviY5jeQbUUkVc1hZSQ9I/YtB3KB/2VT7zME+AT/inolohJ6RHCwFt+gctmKsfrLHqc/bsa3dDAo5/Sxaqabl56WCoPjl3auNoJltoRdj8RaxkSKe85o0ph+oK+XSGdk4IAVUsvzJEYB9ptL626h7U3tP5O/le3k3gExicKRy7hGR+yYUeTKkwDA=
  template:
    metadata:
      creationTimestamp: null
      name: htpasswd
      namespace: openshift-config

