---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yougo-team-admin
  namespace: yougo-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: yougo-team
  namespace: yougo-dev
- kind: Group
  name: yougo-team


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yougo-team-admin
  namespace: yougo-cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: yougo-team
  namespace: yougo-cicd
- kind: Group
  name: yougo-team

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yougo-team-admin
  namespace: yougo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: yougo-team
  namespace: yougo
- kind: Group
  name: yougo-team
