apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: namespace-configuration-operator
resources:
  - namespace.yml
  - https://raw.githubusercontent.com/redhat-cop/namespace-configuration-operator/v1.2.4/config/operatorhub/operator.yaml
