---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-hostmount-anyuid
  namespace: default
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - hostmount-anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: use-scc-hostmount-anyuid
  namespace: default
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner
  namespace: default
roleRef:
  kind: Role
  name: use-scc-hostmount-anyuid
  apiGroup: rbac.authorization.k8s.io
