apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/fluxcd/flux2/manifests/install?ref=v0.13.1
patches:
- path: patches/remove-fsgroup.yml
  target:
    kind: Deployment
    name: (kustomize|source|image-reflector|image-automation)-controller