apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: cluster-config
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/stocky37/ocp-config.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: default
spec:
  interval: 10m0s
  path: .
  prune: true
  sourceRef:
    name: cluster-config
    kind: GitRepository
  validation: client
