apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
  namespace: flux
spec:
  template:
    spec:
      containers:
      - name: flux
        args:
          - --memcached-service=
          - --ssh-keygen-dir=/var/fluxd/keygen
          - --git-url=https://github.com/stocky37/homelab-k8s.git
          - --git-branch=main
          - --git-readonly
          - --git-poll-interval=1m
          - --listen-metrics=:3031
          - --manifest-generation=true
          - --registry-disable-scanning=true
          - --sync-garbage-collection=true
