apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-config
spec:
  destination:
    name: ''
    namespace: ''
    server: 'https://kubernetes.default.svc'
  source:
    path: clusters/homelab
    repoURL: 'https://github.com/stocky37/ocp-config.git'
    targetRevision: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
