name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  v4-homelab-flux:
    name: homelab/flux [Kustomize v4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run kustomize build
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '4.1.2'
          kustomize_build_dir: clusters/homelab/flux
          kustomize_build_options: --load-restrictor LoadRestrictionsNone
  
  v4-homelab-core:
    name: homelab/core [Kustomize v4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run kustomize build
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '4.1.2'
          kustomize_build_dir: clusters/homelab/core
          kustomize_build_options: --load-restrictor LoadRestrictionsNone

  v3-homelab-flux:
    name: homelab/flux [Kustomize v3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run kustomize build
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.10.0'
          kustomize_build_dir: clusters/homelab/flux
          kustomize_build_options: --load_restrictor LoadRestrictionsNone
  
  v3-homelab-core:
    name: homelab/core [Kustomize v3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run kustomize build
        uses: karancode/kustomize-github-action@master
        with:
          kustomize_version: '3.10.0'
          kustomize_build_dir: clusters/homelab/core
          kustomize_build_options: --load_restrictor LoadRestrictionsNone