apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../infra/gitops

patches:
  - path: patches/applicationset-common.yml
    target:
      kind: ApplicationSet

  - path: patches/applicationset-cluster-config.yml
    target:
      kind: ApplicationSet
      name: cluster-config
